// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RawImageMsg.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__SENSOR_RAWIMAGEMSG_HPP
#define FAST_DDS_GENERATED__SENSOR_RAWIMAGEMSG_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RAWIMAGEMSG_SOURCE)
#define RAWIMAGEMSG_DllAPI __declspec( dllexport )
#else
#define RAWIMAGEMSG_DllAPI __declspec( dllimport )
#endif // RAWIMAGEMSG_SOURCE
#else
#define RAWIMAGEMSG_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RAWIMAGEMSG_DllAPI
#endif // _WIN32

namespace sensor {

/*!
 * @brief This class represents the structure RawImageMsg defined by the user in the IDL file.
 * @ingroup RawImageMsg
 */
class RawImageMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport RawImageMsg()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~RawImageMsg()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object RawImageMsg that will be copied.
     */
    eProsima_user_DllExport RawImageMsg(
            const RawImageMsg& x)
    {
                    m_timestamp = x.m_timestamp;

                    m_format = x.m_format;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object RawImageMsg that will be copied.
     */
    eProsima_user_DllExport RawImageMsg(
            RawImageMsg&& x) noexcept
    {
        m_timestamp = x.m_timestamp;
        m_format = std::move(x.m_format);
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object RawImageMsg that will be copied.
     */
    eProsima_user_DllExport RawImageMsg& operator =(
            const RawImageMsg& x)
    {

                    m_timestamp = x.m_timestamp;

                    m_format = x.m_format;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object RawImageMsg that will be copied.
     */
    eProsima_user_DllExport RawImageMsg& operator =(
            RawImageMsg&& x) noexcept
    {

        m_timestamp = x.m_timestamp;
        m_format = std::move(x.m_format);
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x RawImageMsg object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const RawImageMsg& x) const
    {
        return (m_timestamp == x.m_timestamp &&
           m_format == x.m_format &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x RawImageMsg object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const RawImageMsg& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            int32_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport int32_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport int32_t& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function copies the value in member format
     * @param _format New value to be copied in member format
     */
    eProsima_user_DllExport void format(
            const std::string& _format)
    {
        m_format = _format;
    }

    /*!
     * @brief This function moves the value in member format
     * @param _format New value to be moved in member format
     */
    eProsima_user_DllExport void format(
            std::string&& _format)
    {
        m_format = std::move(_format);
    }

    /*!
     * @brief This function returns a constant reference to member format
     * @return Constant reference to member format
     */
    eProsima_user_DllExport const std::string& format() const
    {
        return m_format;
    }

    /*!
     * @brief This function returns a reference to member format
     * @return Reference to member format
     */
    eProsima_user_DllExport std::string& format()
    {
        return m_format;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<uint8_t>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<uint8_t>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<uint8_t>& data()
    {
        return m_data;
    }



private:

    int32_t m_timestamp{0};
    std::string m_format;
    std::vector<uint8_t> m_data;

};

} // namespace sensor

#endif // _FAST_DDS_GENERATED_SENSOR_RAWIMAGEMSG_HPP_


